[mypy]
python_version = 3.13
disallow_untyped_defs = False
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
explicit_package_bases = True
strict_optional = False

[mypy-tests.*]
ignore_errors = True

[mypy-backend.app.api.*]
ignore_errors = True

[mypy-backend.app.services.*]
ignore_errors = True

[mypy-backend.app.db.*]
ignore_errors = True

[mypy-backend.app.models.*]
ignore_errors = True

[mypy-backend.app.infrastructure.adapters.*]
ignore_errors = True
